{
    'name': "App Onee",
    'author': "Ibrahem Issa",
    'license': 'LGPL-3',
    'category': "Uncategorized",
    'version': '19.0.0.1.0',
    'depends': ['base','account','sale','mail','contacts'],
    'data': [
        'security/security_group.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data.xml',
        'views/baes_menu.xml',
        'views/property_view.xml',
        'views/owner_view.xml',
        'views/tag_view.xml',
        'views/sale_order.xml',
        'views/res_partner_view.xml',
        'views/building_view.xml',
        'views/property_history_view.xml',
        'views/account_view.xml',
        'wizard/change_state_wizard_view.xml',
        'reports/property_report.xml',

    ],
    'assets': {
    'web.assets_backend': [
        'app_onee/static/src/components/listview/listView.css',
        'app_onee/static/src/components/listview/listView.js',
        'app_onee/static/src/components/listview/listView.xml',
    ],
},
    'application': True,
    'installable': True,
}